### ISSUE TITLE
Abnormally increasing RAM consumption while playing Minecraft Beta 1.7.3 (OpenGL) 

### ISSUE THREAD

**Issue by MrWrightD7A** [GPUOpen-Drivers/AMD-Gfx-Drivers#15] opened 2024-07-16 10:13 UTC
Good afternoon, everyone!
![Снимок экрана 2024-04-21 121745](https://github.com/user-attachments/assets/8a7c5930-a441-494d-89ff-de6c389f28d0)

During game sessions in Minecraft Beta 1.7.3 (using Java there is an abnormal increase in the game's RAM consumption. The growth is gradual: every 1-2 seconds the game "eats" 10-50 or even 100 megabytes of RAM. Which then, in the end, after 15-20 minutes, leads to the game hangs and the laptop RAM filled to the ceiling.

I asked the administration of the server (on which I play this version of Minecraft) on this matter. They replied that it might be due to a memory leak in the AMD driver. But we decided to try to fix this problem ourselves, having tried all possible solutions: from game settings/JVM-arguments to driver settings. But nothing helped - the game continued to "eat" memory.

 

Then I decided to try running the game on a Linux Mint distribution with all the latest updates and drivers. And strangely enough, Minecraft didn't even try to "eat up" the whole memory. Its RAM consumption was kept at the level of 600-800 megabytes and no more. That is, the problem (probably) is really in the AMD driver on Windows (because everything works perfectly under Linux).

 

Also, I decided to try rolling back from the new version of AMD driver for Windows to the old one - no result. Also, I asked other server players, who like me play on laptops/computers with integrated AMD video chips - the problem is the same for all of them. But only one of them, who had an old version of the driver (30.0.14023.7007), had everything normal and the game did not "eat up" the whole memory. But I decided not to install (for now) the version of the driver on which the last mentioned player is playing.

Of course, I reported this problem via AMD Bug Report Tool as well. But additionally, to speed up the process somehow, I decided to share it on the forum. Maybe someone else has also encountered a typical unpleasant mishap...

Laptop Characteristics:

    AMD graphics card: Radeon Vega 8
    Notebook: TECNO Mobile Limited MEGABOOK T15DA
    Operating System: Windows 11 64bit 23H2 22631.3527
    Driver version: Radeon Software Adrenaline 24.3.1
    AMD processor: AMD Ryzen 7 5800U
    RAM: LPDDR4 16 Gigabytes 4266 MHz

Thanks for your attention!

**Comment by DonglinWei2018** [comment] 2024-07-17 07:41
Thanks for reporting this issue. To facilitate our issue investigation from AMD OpenGL driver perspective, could you share the save file for us to reproduce your issue ?

**Comment by MrWrightD7A** [comment] 2024-07-17 20:43
> Thanks for reporting this issue. To facilitate our issue investigation from AMD OpenGL driver perspective, could you share the save file for us to reproduce your issue ?

Thank you for bringing attention to this problem! I'm just not sure what you mean by ‘save file’. Do you mean the Minecraft map file, or something else? Simply, I encountered this problem exactly in Minecraft Beta 1.7.3 - both when playing on a multiplayer server and in single-player)

**Comment by Slaw6820** [comment] 2024-07-18 06:44
@MrWrightD7A 
Yes, Minecraft map file that can be loaded to reproduce the issue with the same exact level/map/world as yours

**Comment by MrWrightD7A** [comment] 2024-07-18 11:06
All right. Here you go. Run it on Minecraft Beta 1.7.3.
[New World.zip](https://github.com/user-attachments/files/16282083/New.World.zip)
P.S. The problem with abnormal RAM/VRAM consumption in older versions of Minecraft is observed from AMD Adrenalin 22.7.1 Optional driver version to all the latest versions.

**Comment by DonglinWei2018** [comment] 2024-07-23 07:07
> All right. Here you go. Run it on Minecraft Beta 1.7.3. [New World.zip](https://github.com/user-attachments/files/16282083/New.World.zip) P.S. The problem with abnormal RAM/VRAM consumption in older versions of Minecraft is observed from AMD Adrenalin 22.7.1 Optional driver version to all the latest versions.

Thanks. We have successfully reproduced this issue, and the root cause is understood. A driver fix will be verified which will be included into future Adrenalin driver releases.

**Comment by MrWrightD7A** [comment] 2024-07-23 11:02
> > All right. Here you go. Run it on Minecraft Beta 1.7.3. [New World.zip](https://github.com/user-attachments/files/16282083/New.World.zip) P.S. The problem with abnormal RAM/VRAM consumption in older versions of Minecraft is observed from AMD Adrenalin 22.7.1 Optional driver version to all the latest versions.
> 
> Thanks. We have successfully reproduced this issue, and the root cause is understood. A driver fix will be verified which will be included into future Adrenalin driver releases.

Well done! Thank you for your attention and work on this problem!

**Comment by MrWrightD7A** [comment] 2024-07-29 19:59
Good afternoon! I updated to a new driver version - 24.7.1. Unfortunately, the problem still remains(

But! If before (on drivers before version 24.7.1) RAM was clogged after 15-20 minutes approximately, now this time has increased. Now, on driver version 24.7.1, the memory fills up in 30-40 minutes.

**Comment by baozholu-AMD** [comment] 2024-07-30 08:27
> Good afternoon! I updated to a new driver version - 24.7.1. Unfortunately, the problem still remains(
> 
> But! If before (on drivers before version 24.7.1) RAM was clogged after 15-20 minutes approximately, now this time has increased. Now, on driver version 24.7.1, the memory fills up in 30-40 minutes.

Hi, the fix is not yet included into the Adrenalin driver releases

**Comment by MrWrightD7A** [comment] 2024-07-30 11:03
> > Good afternoon! I updated to a new driver version - 24.7.1. Unfortunately, the problem still remains(
> > But! If before (on drivers before version 24.7.1) RAM was clogged after 15-20 minutes approximately, now this time has increased. Now, on driver version 24.7.1, the memory fills up in 30-40 minutes.
> 
> Hi, the fix is not yet included into the Adrenalin driver releases

Okay, I get it. So the fix will be in the next driver release (after 24.7.1)?

**Comment by baozholu-AMD** [comment] 2024-08-01 03:36
> > Hi, the fix is not yet included into the Adrenalin driver releases
> 
> Okay, I get it. So the fix will be in the next driver release (after 24.7.1)?

I will notify you if I get any update on this.

**Comment by DonglinWei2018** [comment] 2024-08-15 07:16
> > > Good afternoon! I updated to a new driver version - 24.7.1. Unfortunately, the problem still remains(
> > > But! If before (on drivers before version 24.7.1) RAM was clogged after 15-20 minutes approximately, now this time has increased. Now, on driver version 24.7.1, the memory fills up in 30-40 minutes.
> > 
> > 
> > Hi, the fix is not yet included into the Adrenalin driver releases
> 
> Okay, I get it. So the fix will be in the next driver release (after 24.7.1)?

The fix is expected to land in 24.8.1 Adrenalin release. Please check it out later on.

**Closed as completed** 2024-09-03 01:54 UTC
Labels: fixed, Windows, OpenGL

**Comment by DonglinWei2018** [comment] 2024-09-04 07:38
@MrWrightD7A  The fix is rolled into Adrenalin 24.8.1 release already: https://www.amd.com/en/resources/support-articles/release-notes/RN-RAD-WIN-24-8-1.html. Could you verify this issue with this new driver release ?

**Comment by MrWrightD7A** [comment] 2024-09-07 14:41
> @MrWrightD7A The fix is rolled into Adrenalin 24.8.1 release already: https://www.amd.com/en/resources/support-articles/release-notes/RN-RAD-WIN-24-8-1.html. Could you verify this issue with this new driver release ?

Hello. Okay, I'm going to test how this new driver version works with the game. I will report the results soon.

**Comment by MrWrightD7A** [comment] 2024-09-07 14:59
@DonglinWei2018 When installing the driver version that you have linked to, error number 182 is displayed. Even after using the AMD Cleanup utility, the error does not disappear.

**Comment by baozholu-AMD** [comment] 2024-10-28 08:30
@MrWrightD7A The latest driver is Adrenalin 24.10.1, does the "Abnormally increasing RAM consumption" issue disappear on the latest driver ?
